name: push_check_and_send_report
run-name: ${{github.actor}} push check and send report
on: 
    push:
        tags: 
            - v[0-9]+.[0-9]+
               
jobs:
    Begin-Check:
        name: Check_Commit_Message
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v3

            - name: Check Commit Message
              run: |
                commit_message=$(git log -1 --pretty=%B)
                echo "commit message: $commit_message"
                if [[ $commit_message == "#NORUN"* ]]; then
                  echo "Commit message starts with #NORUN. Skipping workflow."
                  exit 1  
                else
                  echo "Commit message does not start with #NORUN. Continuing workflow."
                fi
            

            - name: Trivy Scan
              uses: aquasecurity/trivy-action@master
              with:
                scan-type: 'fs'
                ignore-unfixed: true
                format: 'table'
                output: 'trivy-results.table'
                severity: '${{ github.event.inputs.NAME }}'
              
            - name: Check Trivy Results
              run: |
                result_len=$(wc -c < trivy-results.table)
                echo $result_len 
                if [[ $result_len == 0 ]]; then
                  echo "No vulnerabilities found. Exiting."
                  exit 1
                else
                  echo "Vulnerabilities found. Continuing workflow."
                fi
                cat trivy-results.table > trivy-results.txt

              
            - name: Send Fail Report
              uses: rtCamp/action-slack-notify@v2
              env:
                 SLACK_CHANNEL: test-submission
                 SLACK_COLOR: Ff0000
                 SLACK_MESSAGE: 'Find vulnerabilities, failed. :rocket:'
                 SLACK_TITLE: Scan Failed -${{ secrets.NAME }}
                 SLACK_USERNAME: ${{ secrets.NAME }}
                 SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
                 SLACK_FOOTER: 'Power by Hipper'

            - name: Upload Fail Report
              uses: MeilCli/slack-upload-file@v3
              with:
                 slack_token: ${{ secrets.SLACK_TOKEN }}
                 channel_id: ${{ secrets.SLACK_CHANNEL_ID }}
                 file_path: 'trivy-results.txt'
                 initial_comment: 'post by Yu Zejing'
            

    success-package:
        name: Success_Package
        runs-on: ubuntu-latest
        needs: Begin-Check
        if: failure()
        steps:
          -
            name: Checkout
            uses: actions/checkout@v3
          -
            name: Set up QEMU
            uses: docker/setup-qemu-action@v3
          -
            name: Set up Docker Buildx
            uses: docker/setup-buildx-action@v3
          -
            name: Login to Docker Hub
            uses: docker/login-action@v3
            with:
              username: ${{ secrets.DOCKERHUB_USERNAME }}
              password: ${{ secrets.DOCKERHUB_TOKEN }}
          -
            name: Build and push
            uses: docker/build-push-action@v5
            with:
              push: true
              tags: user/ca01:${{ github.sha }}


          # - name: Send Success Report
          #   uses: rtCamp/action-slack-notify@v2
          #   env:
          #     SLACK_CHANNEL: test-submission
          #     SLACK_COLOR: 00ff00
          #     SLACK_TITLE: Image build and signed -${{ secrets.NAME }}
          #     SLACK_USERNAME: ${{ secrets.NAME }}
          #     SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          #     SLACK_FOOTER: 'Power by Hipper'
          #     SLACK_MESSAGE: |
          #               *Name:* Yu Zejing 
          #               *Matriculation:* A0287259L 
          #               *Email:* <mailto:e1285205@u.nus.edu | e1285205@u.nus.edu> 
          #               *Git:* <${{ github.repository.url }}| ${{ github.repository.url }}> 
          #               *Image:* <${{ github.repository.url }}| ${{ github.repository.url }}> 
                      


