name: push_check_and_send_report
run-name: ${{github.actor}} push check and send report
on: 
    push:
        tags: 
            - v[0-9]+.[0-9]+
               
jobs:
    build:
        name: Check_Commit_Message
        runs-on: ubuntu-latest
        steps:
            - name: Check Commit Message
              run: |
                commit_message=$(git log -1 --pretty=%B)
                if [[ $commit_message == "#NORUN"* ]]; then
                echo "Commit message starts with #NORUN. Skipping workflow."
                exit 0
                fi
    
    trivy-scanning:
        name: Trivy Scanning
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v3

            - name: Trivy Scan
              uses: aquasecurity/trivy-action@master
              with:
                scan-type: 'fs'
                ignore-unfixed: true
                format: 'table'
                output: 'trivy-results.txt'
                severity: 'CRITICAL'